### ISSUE TITLE
Elaboration of MongoDB tables - Database structure. 

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1019]
LDES Server - Snapshot 2.4.0

![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/7da38ddd-170f-4ac3-97ed-628d7c82a81d)
In MongoDB, 14 tables are created once launched the LDES Server. 
Some of them remain empty.
e.g: 
1. fragmentation_allocation
2. ldesfragment
3. ldesmember

It might be a good idea to elaborate on the usage of each table in the doc, for the future open-source community and remove the redundant ones. 

Thanks.

**Comment by rorlic** [comment]
Sorry, I believe it is a very bad idea to elaborate on the document collections: the last thing we want is for people to start depending on these. We need to reserve the freedom to change these as we see fit in order to improve performance or for whatever other reason.

Your concern on the empty collections is however legit: these are remains of a previous server & storage architecture and should ideally be removed.

**Comment by Yalz** [comment]
@rorlic i think it's due to Mongock migrations.. Needs to be looked at.

But I follow you on documenting these tables. We keep track of our DB changes via Mongock which gives an explanation.

If we start writing static code, we are doomed to have documentation errors

**Comment by Yalz** [comment]
TO DO: delete redundant tables after clearing in mongock steps.

**Comment by Tomvbe** [comment]
The application currently only creates the tables that are used. I know that above was an issue in the past but I was not able to reproduce it anymore with the latest server and mongo. Whether or not we should document the usage of the other database collections can be part of https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/346. Since we may migrate to PostgreSQL in the near future, it may be best to wait with this as well.
