### ISSUE TITLE
[README.md] Metrics

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDESServer4J#249]
* currently Metrics are part of the section Developer Information.  Metrics are not specific created for Developers... they have multiple stake holders.
* which metrics standard is being used.
* no specific services (so not related to JVM or Spring) metrics are listed (name, type of metric, purpose)
* related to previous point: mention to exposing of JVM and Spring related metrics.
* scraping interval?
* exposed port? It doesn't seem to be configurable?

in general by more  informative about how metrics are implemented

**Comment by Yalz** [comment]
Hi Daniel,
A lot of these comments are in fact mentioned already on the [dedicated confluence](https://vlaamseoverheid.atlassian.net/wiki/spaces/VSDSPUB/pages/6118410164/Metrics).
* In general, you won't find much info on setting up tracing and metrics in other repos. However we included this in that section so that it can be set up and configured by a developer.
* We adhere to [OpenTelemetry standard](https://opentelemetry.io/docs/concepts/what-is-opentelemetry/), this info is not mentioned here, but on its dedicated confluence page. 
* The scraping interval is not a concern of the exposer, rather of the consumer of the metrics
* The port is not configurable, the metrics are being exposed on the actuator path of spring. Which is configurable (this doesn't seem like the place to document it, but the documentation for it can be found on the docs of Spring). Once again more info is available on the confluence page
