### ISSUE TITLE
[Metrics] Naming 

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDESServer4J#250]
Currently there seem to be only two metric being exposed and these metrics names are hard coded.
* ldes_server_ingested_members => MemberIngestServiceImpl.java
* ldes_server_members_to_fragment => InMemoryFragmentationMediator.java

There is no naming convention but there is a rule which is mostly applied: `naming convention that separates words with a dot, to help guarantee the portability of metric names across multiple monitoring systems`. Another tip is that mostly the metric name indicates which type it is.

Also the service name should not be hard coded but be based on the service name when being deployed.

**Comment by Yalz** [comment]
We indeed have now two metrics. Its name is in line with https://prometheus.io/docs/practices/naming . 

Towards your comment concerning portability, it is a valid one. However, since we expose our metrics using Spring's Prometheus actuator, we try to adhere to these conventions.
The type of the metrics will be included in its name.
