### ISSUE TITLE
Public Classes For Tests Should Not Be Part of the Tests Packages

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDESServer4J#252]
In this project one can notice that specific classes used for testing purpose are part of the implementation package iso test. The general practice is not to add test code to the codebase. 
* Example: TracerMockHelper => TracerMockHelper.java => package be.vlaanderen.informatievlaanderen.ldes.server.domain;

**Comment by Yalz** [comment]
Hi Daniel,

The TracerMockHelper is a small class to mock the sleuth Tracer. This class is located in the test package.
So this shouldn't be in our codebase. Could you verify ?

**Comment by Krieke** [comment]
@Yalz there are apparently two public class TracerMockHelper
* domain/TracerMockHelper.java
* timebased/TracerMockHelper.java

Indeed you are right. They are part of the test package although this was not mentioned in the actual package name `e.a.: package be.vlaanderen.informatievlaanderen.ldes.server.fragmentisers.timebased;` hence my mistake. I notice that none of the test files contain package with test in them. I used to do this, is this not a common practice? => not familiar with Java & Springboot

Maybe other remark: isn't it duplicate code? Or is this because they are used between different modules.

**Comment by Yalz** [comment]
It is indeed not a common practice. Your "test" scope is defined in your folder structure already.
The advantage of not having "test" as a package name is that you can test protected and private methods as long as they are in the same package.

As to your second remark, the funny thing is a bit that you are right (it is duplicate code).
But at the same time, since it is a helper class used over different modules, the only way to share this would be to place in production code. And then we get back to the start of your issue 😉

**Comment by Krieke** [comment]
I can agree with your reasoning
