### ISSUE TITLE
API PUT /admin/api/v1/eventstreams - response "Unrecognized response type after posting the event stream. 200"

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#725]
**Prerequisites:**
1. start the ldes server version:  ldes/ldes-server:1.0.0-SNAPSHOT on the port 8080

**Scenario:**
1. Browser to the the APIs: http://localhost:8080/v1/swagger-ui/index.html#/Event%20Streams/putEventStream
2. Try it out the API : PUT /admin/api/v1/eventstreams
3. Execute the example stream "parcels"

**Current result:**
Server response 200 Ok, but the response body cannot be parsed properly.
with notification:  **_Unrecognized response type; displaying content as text._**
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/0d6e50b6-c31d-4a56-b55c-f4f68a7ee770)

**Expected result:**
There should be no that notification: **_Unrecognized response type; displaying content as text._**
As the response body is in turtle format?

Thanks

**Comment by Yalz** [comment]
Hi @xdxxxdx ,
As RDF is still not a popular standard, popular tools such as openAPI can not handle mime-types such as text/turtle , application/n-quads, ...
This however doesn't limit the user in any way. So I will retract the bug label from it.
You will find this same message spread over all our APIs.

This warning is rather just a warning due to us being too progressive with promoting RDF 😉

**Comment by Tomvbe** [comment]
I agree with @Yalz . Not really a lot we can do about this.. I will close this issue as 'won't fix'. Maybe in a future version of swagger-ui this info message will disappear.

**Comment by xdxxxdx** [comment]
Hello,

That makes sense, thanks for the comment
